from __future__ import annotations

import io
import time
import zipfile
from datetime import datetime

import streamlit as st


MAX_FILE_SIZE_MB = 100


def _is_epub_bytes(data: bytes) -> bool:
    """Check EPUB container signature quickly."""
    return data.startswith(b"PK")


def _inspect_epub(data: bytes) -> dict:
    """Read simple EPUB stats for demo display."""
    stats = {
        "entries": 0,
        "chapter_like_files": 0,
        "has_opf": False,
    }

    with zipfile.ZipFile(io.BytesIO(data), "r") as zf:
        names = zf.namelist()
        stats["entries"] = len(names)
        stats["chapter_like_files"] = sum(
            1 for n in names if n.lower().endswith((".xhtml", ".html", ".htm"))
        )
        stats["has_opf"] = any(n.lower().endswith(".opf") for n in names)

    return stats


def _build_demo_epub3(data: bytes, source_name: str) -> tuple[bytes, str]:
    """
    Build a demo output EPUB by copying all original entries and appending
    a demo marker file. This simulates a processed EPUB3 artifact.
    """
    output = io.BytesIO()

    with zipfile.ZipFile(io.BytesIO(data), "r") as src:
        with zipfile.ZipFile(output, "w") as dst:
            for info in src.infolist():
                dst.writestr(info, src.read(info.filename))

            marker = (
                "Demo output generated by Streamlit app\n"
                f"Source: {source_name}\n"
                f"Generated: {datetime.utcnow().isoformat()}Z\n"
                "Mode: local-demo\n"
            )
            dst.writestr("META-INF/demo-processed.txt", marker)

    output.seek(0)
    base_name = source_name.rsplit(".", 1)[0] if "." in source_name else source_name
    out_name = f"{base_name}_epub3_demo.epub"
    return output.read(), out_name


def main() -> None:
    st.set_page_config(page_title="Audiobook EPUB3 Demo", page_icon="📚", layout="centered")

    st.title("Audiobook Generation System")
    st.caption("Upload EPUB, simulate processing pipeline, download EPUB3 demo output.")

    with st.expander("Demo scope", expanded=False):
        st.write("- This is a quick demo UI for deployment testing.")
        st.write("- Processing is simulated locally in Streamlit.")
        st.write("- Output file is an EPUB container with a demo marker.")

    uploaded = st.file_uploader("Upload EPUB file", type=["epub"])

    process_clicked = st.button("Start processing", type="primary", use_container_width=True)

    if process_clicked:
        if uploaded is None:
            st.error("Please upload an EPUB file first.")
            return

        data = uploaded.read()
        size_mb = len(data) / (1024 * 1024)

        if size_mb > MAX_FILE_SIZE_MB:
            st.error(f"File too large: {size_mb:.1f} MB (max {MAX_FILE_SIZE_MB} MB).")
            return

        if not _is_epub_bytes(data):
            st.error("Invalid EPUB file: ZIP signature not found.")
            return

        try:
            stats = _inspect_epub(data)
        except Exception as exc:
            st.error(f"Cannot parse EPUB: {exc}")
            return

        st.info(
            "Detected EPUB with "
            f"{stats['entries']} entries, "
            f"{stats['chapter_like_files']} chapter-like files, "
            f"OPF present: {stats['has_opf']}"
        )

        progress = st.progress(0)
        status = st.empty()

        steps = [
            "Validating EPUB structure",
            "Extracting chapters and metadata",
            "Preparing narration pipeline",
            "Generating synchronized package",
            "Finalizing EPUB3 output",
        ]

        for idx, step in enumerate(steps, start=1):
            status.write(f"Step {idx}/{len(steps)}: {step}")
            for p in range(5):
                pct = int(((idx - 1) * 20) + (p + 1) * 4)
                progress.progress(min(pct, 100))
                time.sleep(0.08)

        out_bytes, out_name = _build_demo_epub3(data, uploaded.name)

        st.success("Processing completed.")
        st.download_button(
            label="Download EPUB3 demo",
            data=out_bytes,
            file_name=out_name,
            mime="application/epub+zip",
            use_container_width=True,
        )


if __name__ == "__main__":
    main()
