from __future__ import annotations

import io
import os
import time
import tempfile
import asyncio
import sys
import zipfile
from datetime import datetime, timezone

# Thêm thư mục src vào PATH để có thể import agents
sys.path.append(os.path.join(os.path.dirname(__file__), "src"))

import streamlit as st


MAX_FILE_SIZE_MB = 100


def _is_epub_bytes(data: bytes) -> bool:
    """Check EPUB container signature quickly."""
    return data.startswith(b"PK")


def _inspect_epub(data: bytes) -> dict:
    """Read simple EPUB stats for demo display."""
    stats = {
        "entries": 0,
        "chapter_like_files": 0,
        "has_opf": False,
    }

    with zipfile.ZipFile(io.BytesIO(data), "r") as zf:
        names = zf.namelist()
        stats["entries"] = len(names)
        stats["chapter_like_files"] = sum(
            1 for n in names if n.lower().endswith((".xhtml", ".html", ".htm"))
        )
        stats["has_opf"] = any(n.lower().endswith(".opf") for n in names)

    return stats


def _build_demo_epub3(data: bytes, source_name: str) -> tuple[bytes, str]:
    """
    Build a demo output EPUB by copying all original entries and appending
    a demo marker file. This simulates a processed EPUB3 artifact.
    """
    output = io.BytesIO()

    with zipfile.ZipFile(io.BytesIO(data), "r") as src:
        with zipfile.ZipFile(output, "w") as dst:
            for info in src.infolist():
                dst.writestr(info, src.read(info.filename))

            marker = (
                "Demo output generated by Streamlit app\n"
                f"Source: {source_name}\n"
                f"Generated: {datetime.now(timezone.utc).isoformat()}Z\n"
                "Mode: local-demo\n"
            )
            dst.writestr("META-INF/demo-processed.txt", marker)

    output.seek(0)
    base_name = source_name.rsplit(".", 1)[0] if "." in source_name else source_name
    out_name = f"{base_name}_epub3_demo.epub"
    return output.read(), out_name


# Add src to sys.path using absolute path
src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "src"))
if src_path not in sys.path:
    sys.path.insert(0, src_path)

try:
    from agents import CleanerAgent, CleanerInput, ClassifierAgent, ClassifierInput
except ImportError as e:
    st.error(f"❌ Lỗi Import Agents: {e}")
    st.info(f"Đường dẫn hiện tại: {os.getcwd()}")
    st.info(f"PYTHONPATH: {sys.path[:3]}")


def _normalize_label(label: str | None) -> str:
    """Normalize labels like 'chien_tranh' to 'Chiến tranh'."""
    if not label:
        return "N/A"
    # Replace underscores with spaces and capitalize the first letter
    normalized = label.replace("_", " ")
    return normalized.capitalize()


def main() -> None:
    st.set_page_config(
        page_title="Hệ thống tạo Audiobook", page_icon="🎧", layout="wide"
    )

    st.title("🎧 Hệ thống tạo Audiobook")
    st.markdown("### Demo Pipeline AI Agentic")

    with st.sidebar:
        st.header("Cài đặt")
        normalize = st.checkbox("Chuẩn hóa âm thanh", value=True)
        remove_noise = st.checkbox("Làm sạch nâng cao", value=True)
        st.divider()
        st.info(
            "Giao diện này sử dụng các Agent Cleaner và Classifier thực tế (PhoBERT)."
        )

    uploaded = st.file_uploader("Tải lên file EPUB", type=["epub"])

    if uploaded:
        col1, col2 = st.columns([1, 1])

        with col1:
            st.info(
                f"Đã tải lên: {uploaded.name} ({len(uploaded.getvalue())/1024/1024:.2f} MB)"
            )
            process_clicked = st.button(
                "🚀 Bắt đầu Pipeline Agentic", type="primary", use_container_width=True
            )

        if process_clicked:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".epub") as tmp:
                tmp.write(uploaded.getvalue())
                tmp_path = tmp.name

            try:
                progress_bar = st.progress(0)
                status_text = st.empty()

                # --- START PIPELINE ---
                from pipeline import AudiobookPipeline, PipelineConfig

                config = PipelineConfig(
                    input_file=tmp_path,
                    output_dir="temp_output",
                    normalize_audio=normalize,
                    add_chapters=True,
                )

                pipeline = AudiobookPipeline(config)

                # Execute Pipeline with real-time polling
                start_total = time.time()

                async def run_and_poll():
                    task = asyncio.create_task(pipeline.run_analysis())
                    while not task.done():
                        state_dict = pipeline.state.to_dict()
                        progress_val = min(1.0, state_dict.get("progress", 0.0))
                        progress_bar.progress(progress_val)

                        msg = state_dict.get("status_message", "")
                        curr_ch = state_dict.get("current_chapter", 0)
                        total_ch = state_dict.get("total_chapters", 0)

                        display_msg = (
                            f"**Giai đoạn:** {state_dict.get('stage', '').upper()}"
                        )
                        if msg:
                            display_msg += f"\n\n**Trạng thái:** {msg}"
                        if total_ch > 0:
                            display_msg += (
                                f"\n\n**Tiến độ chương:** {curr_ch}/{total_ch}"
                            )

                        status_text.markdown(display_msg)
                        await asyncio.sleep(0.2)
                    return await task

                result = asyncio.run(run_and_poll())

                if not result["success"]:
                    st.error(f"Pipeline thất bại: {result.get('error')}")
                    st.stop()

                total_duration = time.time() - start_total

                # Extract results from Phase 1 unified demo
                class_res_data = result["classify"]
                ctx = result["summarize"]

                progress_bar.progress(100)
                status_text.write(f"✅ Pipeline hoàn tất trong {total_duration:.2f}s.")

                # --- RESULTS DISPLAY ---
                with col2:
                    st.success("🎯 Pipeline Preprocessing đã hoàn tất!")

                    # ── Row 1: Core metrics ──────────────────────────────
                    st.subheader("📊 Phân tích tổng thể")
                    m1, m2, m3, m4 = st.columns(4)
                    m1.metric("Thể loại", _normalize_label(class_res_data.genre))
                    m2.metric("Mood chủ đạo", class_res_data.mood)
                    m3.metric(
                        "Tỉ lệ thoại",
                        f"{getattr(class_res_data, 'dialogue_ratio', 0):.1%}",
                    )
                    m4.metric("Số chương", result.get("chapter_count", "N/A"))

                    # ── Row 2: Voice style recommendation ───────────────
                    voice_style = getattr(
                        class_res_data, "recommended_voice_style", None
                    )
                    if voice_style:
                        st.info(f"🎙️ **Giọng đọc đề xuất:** {voice_style}")

                    # ── Row 3: Entities & Keywords ───────────────────────
                    c1, c2 = st.columns(2)
                    with c1:
                        st.write("**Nhân vật định danh:**")
                        st.caption(
                            ", ".join(ctx.entities) if ctx.entities else "Không rõ"
                        )
                    with c2:
                        st.write("**Từ khóa định hướng:**")
                        st.caption(
                            ", ".join(ctx.keywords[:5]) if ctx.keywords else "N/A"
                        )

                    # ── Book summary ─────────────────────────────────────
                    with st.expander("📝 Tóm tắt toàn tác phẩm"):
                        st.info(ctx.summary if ctx.summary else "Chưa có dữ liệu.")

                    # ── Chapter summaries ────────────────────────────────
                    chapter_summaries = getattr(ctx, "chapter_summaries", [])
                    chapters = result.get("chapters", [])
                    if chapter_summaries:
                        with st.expander(
                            f"📚 Tóm tắt từng chương ({len(chapter_summaries)} chương)"
                        ):
                            for i, ch_sum in enumerate(chapter_summaries):
                                ch_title = (
                                    chapters[i].title
                                    if i < len(chapters)
                                    else f"Chương {i+1}"
                                )
                                st.markdown(f"**{ch_title}**")
                                st.caption(ch_sum if ch_sum else "_Không có nội dung._")
                                st.divider()

                    # ── Emotion distribution ─────────────────────────────
                    st.subheader("🔍 Chi tiết phân loại theo ngữ cảnh")
                    sentences = getattr(class_res_data, "sentences", [])
                    if sentences:
                        from collections import Counter

                        emotions = [s["emotion"] for s in sentences]
                        emo_counts = Counter(emotions)
                        total = len(sentences)

                        st.write("**Phân bổ cảm xúc:**")
                        emo_cols = st.columns(min(len(emo_counts), 4))
                        for i, (emo, count) in enumerate(emo_counts.most_common(4)):
                            emo_cols[i % 4].metric(emo, f"{count/total:.1%}")

                        st.divider()

                        sent_data = []
                        for s in sentences[:30]:
                            sent_data.append(
                                {
                                    "Câu văn": s["text"][:100] + "...",
                                    "Loại": (
                                        "Thoại" if s["type"] == "dialogue" else "Kể"
                                    ),
                                    "Cảm xúc": s["emotion"],
                                    "Nhân vật": s["speaker"],
                                }
                            )
                        st.table(sent_data)
                    else:
                        st.info("Không có dữ liệu phân loại câu.")

                    # ── Footer ───────────────────────────────────────────
                    st.divider()
                    st.caption(
                        f"⏱ Tổng thời gian: {total_duration:.1f}s — AudiobookPipeline (Parser → Cleaner → Summarizer → Classifier)"
                    )

            except Exception as e:
                st.error(f"Lỗi pipeline: {e}")
                import traceback

                st.code(traceback.format_exc())

        else:
            st.info("👋 Vui lòng tải lên file EPUB để bắt đầu.")


if __name__ == "__main__":
    main()
